module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    screens: {
      xsMobile: '285px',
      smMobile: '320px',
      mobile: '375px',
      lgMobile: '425px',
      xsTablet: '500px',
      smTablet: '650px',
      tablet: '768px',
      mdTablet: '784px',
      lgTablet: '800px',
      smLaptop: '850px',
      laptop: '1000px',
      mdHeight: { raw: '(min-height: 850px)' },
      lgHeight: { raw: '(min-height: 1000px)' },
    },
    colors: {
      dark: '#222',
      white: '#fff',
      light: '#fff',
      blue: '#679cdf',
      'light-blue': '#f6f9fc',
      'dark-blue': '#2f363d',
      purple: '#48bb78',
      green: '#9f7aea',
      pink: '#ed64a6',
      gold: '#ffdf5d',
      black: '#000',
      transparent: 'transparent',
      current: 'currentColor',
      accent: 'var(--accent-color)',
    },
    fontFamily: {
      sans: [
        '"Space Grotesk"',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      mono: [
        '"Space Mono"',
        'ui-monospace',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        '"Liberation Mono"',
        '"Courier New"',
        'monospace',
      ],
    },
    fontSize: {
      xs: '12px',
      sm: '14px',
      base: '16px',
      lg: '20px',
      xl: '25px',
      '2xl': '28px',
      '3xl': '30px',
      '4xl': '32px',
      '5xl': '45px',
      '5vw': '5vw',
      '7vw': '7vw',
      '8vw': '8vw',
    },
    spacing: {
      0: '0',
      1: '2px',
      2: '5px',
      3: '8px',
      4: '10px',
      5: '12px',
      6: '15px',
      7: '20px',
      8: '25px',
      9: '30px',
      10: '40px',
      11: '60px',
      12: '70px',
    },
    letterSpacing: {
      normal: '0',
      wide: '2px',
    },
    borderRadius: {
      none: '0',
      sm: '5px',
      DEFAULT: '50%',
    },
    animation: {
      wave: '3s ease-in-out infinite wave',
    },
    keyframes: {
      wave: {
        '0%, 20%, 40%, 100%': {
          transform: 'rotate(0deg)',
        },
        '10%': {
          transform: 'rotate(-20deg)',
        },
        '30%': {
          transform: 'rotate(-20deg)',
        },
      },
    },
  },
  plugins: [],
};
