export type Job = {
  title: string;
  company: string;
  startDate: string;
  endDate: string;
  skills?: string[];
  about: string[];
};

export const jobs: Job[] = [
  {
    title: 'Senior Software Engineer',
    company: 'Swarm Solutions',
    startDate: 'July 2021',
    endDate: 'Present',
    skills: [
      'JavaScript',
      'TypeScript',
      'Node.js',
      'React.js',
      'Nest.js',
      'AWS',
      'Jest',
      'PostgreSQL',
      'Redis',
    ],
    about: [
      'Develop software applications using best practices in coordination with a distributed team.',
      'Architect complex software features and functionality in a maintainable, DRY, abstract, and modular way.',
      'Demonstrate expert understanding of server-side and client-side JavaScript and asynchronous JavaScript code.',
      'Augment engineering teams and not only deliver quality code, but also demonstrate engineering leadership by being an effective communicator and improving engineering processes.',
    ],
  },
  {
    title: 'Software Developer 2',
    company: 'ResMan Property Management Software',
    startDate: 'January 2020',
    endDate: 'July 2021',
    about: [
      'Joined ResMan when they acquired Razz Interactive.',
      'Developed a custom CMS platform for building marketing websites for real estate and property management professionals.',
      'Worked with designers to build UI/UX for editing responsive websites and reusable components that were robust enough to allow for deep customization, but still easy to use.',
      "Built automation to scrape, scan, and convert pre-existing websites into fully functional responsive web apps on the company's custom CMS product using Google Cloud APIs.",
      'Mentored and developed junior developers. Regularly participated in code reviews.',
      'Investigate JavaScript performance bottlenecks and where we could cut down on bundle sizes to improve load speeds across the entire platform.',
      "Lead discussions and demos on technical topics to share knowledge and insights I'd gained with the rest of the development team, for example: taking still photos with WebRTC.",
      'Actively participated in agile ceremonies and sprint refinement meetings where we work on breaking down larger epics into user smaller stories and estimate how long each story will take.',
    ],
    skills: [
      'Node.js',
      'JavaScript',
      'ES6',
      'MongoDB',
      'Meteor.js',
      'Vue.js',
      'Vuex',
      'GraphQL',
      'JIRA',
      'Webpack',
      'Sass',
      'AWS Lambda',
      'Google Cloud solutions',
    ],
  },
  {
    title: 'Web Developer',
    company: 'Razz Interactive',
    startDate: 'June 2018',
    endDate: 'January 2020',
    about: [
      'Full stack developer for all projects including a new content management system to create and manage marketing websites.',
      'Coded, tested, and maintained corporate websites, web applications, and digital experiences with innovative custom designs.',
      'Translated design mockups into dynamic, optimized, cross-browser compatible, and responsive website templates or reusable components that conform to web accessibility standards and best practices.',
      'Analyzed user needs and technical software requirements to determine feasibility of designs within time and cost constraints.',
      'Followed an agile development workflow and communicate with team members to ship solutions quickly and often.',
      'Built custom Wordpress websites/themes for clients with a Vue frontend.',
      'Wrote technical documentation.',
    ],
    skills: [
      'Node.js',
      'JavaScript',
      'ES6',
      'HTML',
      'CSS',
      'MongoDB',
      'Meteor.js',
      'Vue.js',
      'Asana',
      'PHP',
      'SQL',
      'WordPress',
      'Webpack',
      'Sass',
    ],
  },
  {
    title: 'Web Developer',
    company: 'University of Miami',
    startDate: 'March 2016',
    endDate: 'June 2018',
    about: [
      'Lead Full Stack Developer for a web application that allows firefighters to create timely reports documenting the varied exposures to hazardous environments and toxins they encounter on the job.',
      "Full responsibility over the development and delivery of the app's features, from prototyping to testing to production.",
      'Collaborated with designers to make usability and user experience improvements that are based on user research.',
      'Created and maintained documentation and materials including UML artifacts and user workflows.',
      'Designed a relational database that will also be used by researchers at the university.',
    ],
    skills: [
      'PHP',
      'SQL',
      'Laravel',
      'MVC',
      'jQuery',
      'JavaScript',
      'Relational Database Design',
    ],
  },
  {
    title: 'Web Development Tutor',
    company: 'University of Miami',
    startDate: 'October 2015',
    endDate: 'December 2015',
    about: [
      'Taught front-end web development fundamentals, UI frameworks, and tools.',
      'Helped graduate students in the Interactive Media program troubleshoot/debug their web development projects.',
    ],
  },
  {
    title: 'Teaching Assistant',
    company: 'Girls Who Code',
    startDate: 'June 2014',
    endDate: 'August 2014',
    about: [
      'Part of the inaugural Miami Summer Immersion Program.',
      'Educated and equipped high school women with skills and resources to pursue academics and careers in technology and engineering sectors.',
      'Taught a project-based curriculum on computing concepts, programming fundamentals, algorithms, robotics, and responsive web development.',
      'Managed and supported classroom lectures, discussions, and all other classroom activities, logistics, and administrative business.',
    ],
  },
  {
    title: 'Senior Service Desk Technician',
    company: 'University of Miami',
    startDate: 'September 2013',
    endDate: 'December 2015',
    about: [
      "Provided technical and audio-visual support for the school's classrooms, events, and faculty.",
      'Diagnosed, troubleshooted, and resolved hardware, software, and networking issues.',
      'Interacted with high profile faculty and staff to solve complex issues.',
      'Communicated effectively with users of both technical and non-technical backgrounds.',
      'Oversaw and delegated duties onto a team of 30 student technicians to ensure efficient and effective technical support.',
      'Developed and lead training sessions and demos for incoming technicians.',
    ],
  },
];
